#!/bin/bash
export DATABASE_URL="postgresql://neondb_owner:password@ep-twilight-credit-a15vzonm.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
export NEXT_PUBLIC_SUPABASE_URL="https://hafuhdvifxxkomvwxbql.supabase.co"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZnVoZHZpZnh4a29tdnh3YnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNjU3OTQsImV4cCI6MjA4Nzc0MTc5NH0.iFcWXukuSLS0SpwMCs_q71OU3e8jXIOLG7EGccdJjkE"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZnVoZHZpZnh4a29tdnh3YnFsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE2NTc5NCwiZXhwIjoyMDg3NzQxNzk0fQ.VLSvv2cfrJUWZbLUQ3qPGXzwRci1QpBYU6FhbQF9y14"
